$('input[name="Email"]').val('paul.clarke+test@holidayextras.com');
$(':input[name="Title"]').val('Mr');
$('input[name="Initial"]').val('T');
$('input[name="Surname"]').val('Test');
$('input[name="Registration"]').val('FOO 1');
$('input[name="CarMake"]').val('Ford');
$('input[name="CarModel"]').val('Fiesta');
$('input[name="CarColour"]').val('Blue');
$('input[name="CardNumber"]').val('4111 1111 1111 1111').change( );
$('input[name="CardHolder"]').val('Mr T Test');
$('input[name="CV2"]').val('666');
$(':input[name="expMon"]').val('12');
$(':input[name="expYear"]').val(( new Date( )).getFullYear( ) + 1 );
$(':input[name="flightDetails"][value="no"]').click( );
